use_frameworks!

platform :ios, '9.0'

target 'OwnPodFramework_Example' do
  pod 'OwnPodFramework', :path => '../'

  target 'OwnPodFramework_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
